#include "miles_wire.h"
#include "Mss.h"
#include <type_traits>
static_assert(std::is_function<std::remove_pointer<decltype(&::AIL_WAV_info)>::type>::value,"AIL_WAV_info must be an actual function");
static_assert(std::is_function<std::remove_pointer<decltype(&::AIL_active_sample_count)>::type>::value,"AIL_active_sample_count must be an actual function");
static_assert(std::is_function<std::remove_pointer<decltype(&::AIL_allocate_sample_handle)>::type>::value,"AIL_allocate_sample_handle must be an actual function");
static_assert(std::is_function<std::remove_pointer<decltype(&::AIL_close_stream)>::type>::value,"AIL_close_stream must be an actual function");
static_assert(std::is_function<std::remove_pointer<decltype(&::AIL_digital_CPU_percent)>::type>::value,"AIL_digital_CPU_percent must be an actual function");
static_assert(std::is_function<std::remove_pointer<decltype(&::AIL_digital_latency)>::type>::value,"AIL_digital_latency must be an actual function");
static_assert(std::is_function<std::remove_pointer<decltype(&::AIL_end_sample)>::type>::value,"AIL_end_sample must be an actual function");
static_assert(std::is_function<std::remove_pointer<decltype(&::AIL_file_error)>::type>::value,"AIL_file_error must be an actual function");
static_assert(std::is_function<std::remove_pointer<decltype(&::AIL_file_type)>::type>::value,"AIL_file_type must be an actual function");
static_assert(std::is_function<std::remove_pointer<decltype(&::AIL_get_preference)>::type>::value,"AIL_get_preference must be an actual function");
static_assert(std::is_function<std::remove_pointer<decltype(&::AIL_get_timer_highest_delay)>::type>::value,"AIL_get_timer_highest_delay must be an actual function");
static_assert(std::is_function<std::remove_pointer<decltype(&::AIL_last_error)>::type>::value,"AIL_last_error must be an actual function");
static_assert(std::is_function<std::remove_pointer<decltype(&::AIL_lock)>::type>::value,"AIL_lock must be an actual function");
static_assert(std::is_function<std::remove_pointer<decltype(&::AIL_open_digital_driver)>::type>::value,"AIL_open_digital_driver must be an actual function");
static_assert(std::is_function<std::remove_pointer<decltype(&::AIL_open_stream)>::type>::value,"AIL_open_stream must be an actual function");
static_assert(std::is_function<std::remove_pointer<decltype(&::AIL_register_EOS_callback)>::type>::value,"AIL_register_EOS_callback must be an actual function");
static_assert(std::is_function<std::remove_pointer<decltype(&::AIL_register_stream_callback)>::type>::value,"AIL_register_stream_callback must be an actual function");
static_assert(std::is_function<std::remove_pointer<decltype(&::AIL_release_sample_handle)>::type>::value,"AIL_release_sample_handle must be an actual function");
static_assert(std::is_function<std::remove_pointer<decltype(&::AIL_room_type)>::type>::value,"AIL_room_type must be an actual function");
static_assert(std::is_function<std::remove_pointer<decltype(&::AIL_sample_ms_position)>::type>::value,"AIL_sample_ms_position must be an actual function");
static_assert(std::is_function<std::remove_pointer<decltype(&::AIL_sample_playback_rate)>::type>::value,"AIL_sample_playback_rate must be an actual function");
static_assert(std::is_function<std::remove_pointer<decltype(&::AIL_sample_position)>::type>::value,"AIL_sample_position must be an actual function");
static_assert(std::is_function<std::remove_pointer<decltype(&::AIL_sample_reverb_levels)>::type>::value,"AIL_sample_reverb_levels must be an actual function");
static_assert(std::is_function<std::remove_pointer<decltype(&::AIL_sample_status)>::type>::value,"AIL_sample_status must be an actual function");
static_assert(std::is_function<std::remove_pointer<decltype(&::AIL_sample_volume_levels)>::type>::value,"AIL_sample_volume_levels must be an actual function");
static_assert(std::is_function<std::remove_pointer<decltype(&::AIL_serve)>::type>::value,"AIL_serve must be an actual function");
static_assert(std::is_function<std::remove_pointer<decltype(&::AIL_set_3D_rolloff_factor)>::type>::value,"AIL_set_3D_rolloff_factor must be an actual function");
static_assert(std::is_function<std::remove_pointer<decltype(&::AIL_set_file_callbacks)>::type>::value,"AIL_set_file_callbacks must be an actual function");
static_assert(std::is_function<std::remove_pointer<decltype(&::AIL_set_listener_3D_orientation)>::type>::value,"AIL_set_listener_3D_orientation must be an actual function");
static_assert(std::is_function<std::remove_pointer<decltype(&::AIL_set_listener_3D_position)>::type>::value,"AIL_set_listener_3D_position must be an actual function");
static_assert(std::is_function<std::remove_pointer<decltype(&::AIL_set_listener_3D_velocity_vector)>::type>::value,"AIL_set_listener_3D_velocity_vector must be an actual function");
static_assert(std::is_function<std::remove_pointer<decltype(&::AIL_set_named_sample_file)>::type>::value,"AIL_set_named_sample_file must be an actual function");
static_assert(std::is_function<std::remove_pointer<decltype(&::AIL_set_preference)>::type>::value,"AIL_set_preference must be an actual function");
static_assert(std::is_function<std::remove_pointer<decltype(&::AIL_set_redist_directory)>::type>::value,"AIL_set_redist_directory must be an actual function");
static_assert(std::is_function<std::remove_pointer<decltype(&::AIL_set_room_type)>::type>::value,"AIL_set_room_type must be an actual function");
static_assert(std::is_function<std::remove_pointer<decltype(&::AIL_set_sample_3D_distances)>::type>::value,"AIL_set_sample_3D_distances must be an actual function");
static_assert(std::is_function<std::remove_pointer<decltype(&::AIL_set_sample_3D_position)>::type>::value,"AIL_set_sample_3D_position must be an actual function");
static_assert(std::is_function<std::remove_pointer<decltype(&::AIL_set_sample_3D_velocity_vector)>::type>::value,"AIL_set_sample_3D_velocity_vector must be an actual function");
static_assert(std::is_function<std::remove_pointer<decltype(&::AIL_set_sample_file)>::type>::value,"AIL_set_sample_file must be an actual function");
static_assert(std::is_function<std::remove_pointer<decltype(&::AIL_set_sample_loop_block)>::type>::value,"AIL_set_sample_loop_block must be an actual function");
static_assert(std::is_function<std::remove_pointer<decltype(&::AIL_set_sample_loop_count)>::type>::value,"AIL_set_sample_loop_count must be an actual function");
static_assert(std::is_function<std::remove_pointer<decltype(&::AIL_set_sample_ms_position)>::type>::value,"AIL_set_sample_ms_position must be an actual function");
static_assert(std::is_function<std::remove_pointer<decltype(&::AIL_set_sample_obstruction)>::type>::value,"AIL_set_sample_obstruction must be an actual function");
static_assert(std::is_function<std::remove_pointer<decltype(&::AIL_set_sample_occlusion)>::type>::value,"AIL_set_sample_occlusion must be an actual function");
static_assert(std::is_function<std::remove_pointer<decltype(&::AIL_set_sample_playback_rate)>::type>::value,"AIL_set_sample_playback_rate must be an actual function");
static_assert(std::is_function<std::remove_pointer<decltype(&::AIL_set_sample_position)>::type>::value,"AIL_set_sample_position must be an actual function");
static_assert(std::is_function<std::remove_pointer<decltype(&::AIL_set_sample_reverb_levels)>::type>::value,"AIL_set_sample_reverb_levels must be an actual function");
static_assert(std::is_function<std::remove_pointer<decltype(&::AIL_set_sample_volume_levels)>::type>::value,"AIL_set_sample_volume_levels must be an actual function");
static_assert(std::is_function<std::remove_pointer<decltype(&::AIL_set_stream_loop_block)>::type>::value,"AIL_set_stream_loop_block must be an actual function");
static_assert(std::is_function<std::remove_pointer<decltype(&::AIL_set_stream_loop_count)>::type>::value,"AIL_set_stream_loop_count must be an actual function");
static_assert(std::is_function<std::remove_pointer<decltype(&::AIL_set_stream_ms_position)>::type>::value,"AIL_set_stream_ms_position must be an actual function");
static_assert(std::is_function<std::remove_pointer<decltype(&::AIL_shutdown)>::type>::value,"AIL_shutdown must be an actual function");
static_assert(std::is_function<std::remove_pointer<decltype(&::AIL_speaker_configuration)>::type>::value,"AIL_speaker_configuration must be an actual function");
static_assert(std::is_function<std::remove_pointer<decltype(&::AIL_start_sample)>::type>::value,"AIL_start_sample must be an actual function");
static_assert(std::is_function<std::remove_pointer<decltype(&::AIL_start_stream)>::type>::value,"AIL_start_stream must be an actual function");
static_assert(std::is_function<std::remove_pointer<decltype(&::AIL_startup)>::type>::value,"AIL_startup must be an actual function");
static_assert(std::is_function<std::remove_pointer<decltype(&::AIL_stop_sample)>::type>::value,"AIL_stop_sample must be an actual function");
static_assert(std::is_function<std::remove_pointer<decltype(&::AIL_stream_ms_position)>::type>::value,"AIL_stream_ms_position must be an actual function");
static_assert(std::is_function<std::remove_pointer<decltype(&::AIL_stream_sample_handle)>::type>::value,"AIL_stream_sample_handle must be an actual function");
static_assert(std::is_function<std::remove_pointer<decltype(&::AIL_stream_status)>::type>::value,"AIL_stream_status must be an actual function");
static_assert(std::is_function<std::remove_pointer<decltype(&::AIL_unlock)>::type>::value,"AIL_unlock must be an actual function");
typedef S32 (AILCALL *SampleFile)(HSAMPLE,void const*,S32);
typedef S32 (AILCALL *WavInfo)(void const*,AILSOUNDINFO*);
typedef MSSVECTOR3D* (AILCALL *Speakers)(HDIGDRIVER,S32*,S32*,F32*,MSS_MC_SPEC*);
typedef HSAMPLE (AILCALL *Alias)(HSTREAM);
static_assert(std::is_same<decltype(&::AIL_set_sample_file),SampleFile>::value,"sized adapter preserves vendor signature");
static_assert(std::is_same<decltype(&::AIL_WAV_info),WavInfo>::value,"WAV info signature");
static_assert(std::is_same<decltype(&::AIL_speaker_configuration),Speakers>::value,"speaker pointer signature");
static_assert(std::is_same<decltype(&::AIL_stream_sample_handle),Alias>::value,"borrowed alias signature");
static_assert(sizeof(U32)==4 && sizeof(S32)==4 && sizeof(F32)==4,"scalar widths");
static_assert(sizeof(SINTa)==sizeof(void*),"preference pointer-sized scalar");
