#include "miles_wire.h"
#include "Mss.h"
#include <type_traits>
typedef S32 (AILCALL *Expected1)(void const FAR*, AILSOUNDINFO FAR*);
static_assert(std::is_same<decltype(&::AIL_WAV_info),Expected1>::value,"AIL_WAV_info exact signature");
typedef S32 (AILCALL *Expected2)(HDIGDRIVER);
static_assert(std::is_same<decltype(&::AIL_active_sample_count),Expected2>::value,"AIL_active_sample_count exact signature");
typedef HSAMPLE (AILCALL *Expected3)(HDIGDRIVER);
static_assert(std::is_same<decltype(&::AIL_allocate_sample_handle),Expected3>::value,"AIL_allocate_sample_handle exact signature");
typedef void (AILCALL *Expected4)(HSTREAM);
static_assert(std::is_same<decltype(&::AIL_close_stream),Expected4>::value,"AIL_close_stream exact signature");
typedef S32 (AILCALL *Expected5)(HDIGDRIVER);
static_assert(std::is_same<decltype(&::AIL_digital_CPU_percent),Expected5>::value,"AIL_digital_CPU_percent exact signature");
typedef S32 (AILCALL *Expected6)(HDIGDRIVER);
static_assert(std::is_same<decltype(&::AIL_digital_latency),Expected6>::value,"AIL_digital_latency exact signature");
typedef void (AILCALL *Expected7)(HSAMPLE);
static_assert(std::is_same<decltype(&::AIL_end_sample),Expected7>::value,"AIL_end_sample exact signature");
typedef S32 (AILCALL *Expected8)(void);
static_assert(std::is_same<decltype(&::AIL_file_error),Expected8>::value,"AIL_file_error exact signature");
typedef S32 (AILCALL *Expected9)(void const FAR*, U32);
static_assert(std::is_same<decltype(&::AIL_file_type),Expected9>::value,"AIL_file_type exact signature");
typedef SINTa (AILCALL *Expected10)(U32);
static_assert(std::is_same<decltype(&::AIL_get_preference),Expected10>::value,"AIL_get_preference exact signature");
typedef U32 (AILCALL *Expected11)(void);
static_assert(std::is_same<decltype(&::AIL_get_timer_highest_delay),Expected11>::value,"AIL_get_timer_highest_delay exact signature");
typedef char FAR * (AILCALL *Expected12)(void);
static_assert(std::is_same<decltype(&::AIL_last_error),Expected12>::value,"AIL_last_error exact signature");
typedef void (AILCALL *Expected13)(void);
static_assert(std::is_same<decltype(&::AIL_lock),Expected13>::value,"AIL_lock exact signature");
typedef HDIGDRIVER (AILCALL *Expected14)(U32, S32, S32, U32);
static_assert(std::is_same<decltype(&::AIL_open_digital_driver),Expected14>::value,"AIL_open_digital_driver exact signature");
typedef HSTREAM (AILCALL *Expected15)(HDIGDRIVER, char const FAR *, S32);
static_assert(std::is_same<decltype(&::AIL_open_stream),Expected15>::value,"AIL_open_stream exact signature");
typedef AILSAMPLECB (AILCALL *Expected16)(HSAMPLE, AILSAMPLECB);
static_assert(std::is_same<decltype(&::AIL_register_EOS_callback),Expected16>::value,"AIL_register_EOS_callback exact signature");
typedef AILSTREAMCB (AILCALL *Expected17)(HSTREAM, AILSTREAMCB);
static_assert(std::is_same<decltype(&::AIL_register_stream_callback),Expected17>::value,"AIL_register_stream_callback exact signature");
typedef void (AILCALL *Expected18)(HSAMPLE);
static_assert(std::is_same<decltype(&::AIL_release_sample_handle),Expected18>::value,"AIL_release_sample_handle exact signature");
typedef S32 (AILCALL *Expected19)(HDIGDRIVER);
static_assert(std::is_same<decltype(&::AIL_room_type),Expected19>::value,"AIL_room_type exact signature");
typedef void (AILCALL *Expected20)(HSAMPLE, S32 FAR *, S32 FAR *);
static_assert(std::is_same<decltype(&::AIL_sample_ms_position),Expected20>::value,"AIL_sample_ms_position exact signature");
typedef S32 (AILCALL *Expected21)(HSAMPLE);
static_assert(std::is_same<decltype(&::AIL_sample_playback_rate),Expected21>::value,"AIL_sample_playback_rate exact signature");
typedef U32 (AILCALL *Expected22)(HSAMPLE);
static_assert(std::is_same<decltype(&::AIL_sample_position),Expected22>::value,"AIL_sample_position exact signature");
typedef void (AILCALL *Expected23)(HSAMPLE, F32 FAR *, F32 FAR *);
static_assert(std::is_same<decltype(&::AIL_sample_reverb_levels),Expected23>::value,"AIL_sample_reverb_levels exact signature");
typedef U32 (AILCALL *Expected24)(HSAMPLE);
static_assert(std::is_same<decltype(&::AIL_sample_status),Expected24>::value,"AIL_sample_status exact signature");
typedef void (AILCALL *Expected25)(HSAMPLE, F32 FAR *, F32 FAR *);
static_assert(std::is_same<decltype(&::AIL_sample_volume_levels),Expected25>::value,"AIL_sample_volume_levels exact signature");
typedef void (AILCALL *Expected26)(void);
static_assert(std::is_same<decltype(&::AIL_serve),Expected26>::value,"AIL_serve exact signature");
typedef void (AILCALL *Expected27)(HDIGDRIVER, F32);
static_assert(std::is_same<decltype(&::AIL_set_3D_rolloff_factor),Expected27>::value,"AIL_set_3D_rolloff_factor exact signature");
typedef void (AILCALL *Expected28)(AIL_file_open_callback, AIL_file_close_callback, AIL_file_seek_callback, AIL_file_read_callback);
static_assert(std::is_same<decltype(&::AIL_set_file_callbacks),Expected28>::value,"AIL_set_file_callbacks exact signature");
typedef void (AILCALL *Expected29)(HDIGDRIVER, F32, F32, F32, F32, F32, F32);
static_assert(std::is_same<decltype(&::AIL_set_listener_3D_orientation),Expected29>::value,"AIL_set_listener_3D_orientation exact signature");
typedef void (AILCALL *Expected30)(HDIGDRIVER, F32, F32, F32);
static_assert(std::is_same<decltype(&::AIL_set_listener_3D_position),Expected30>::value,"AIL_set_listener_3D_position exact signature");
typedef void (AILCALL *Expected31)(HDIGDRIVER, F32, F32, F32);
static_assert(std::is_same<decltype(&::AIL_set_listener_3D_velocity_vector),Expected31>::value,"AIL_set_listener_3D_velocity_vector exact signature");
typedef S32 (AILCALL *Expected32)(HSAMPLE, C8 const FAR *, void const FAR *, U32, S32);
static_assert(std::is_same<decltype(&::AIL_set_named_sample_file),Expected32>::value,"AIL_set_named_sample_file exact signature");
typedef SINTa (AILCALL *Expected33)(U32, SINTa);
static_assert(std::is_same<decltype(&::AIL_set_preference),Expected33>::value,"AIL_set_preference exact signature");
typedef char FAR* (AILCALL *Expected34)(char const FAR*);
static_assert(std::is_same<decltype(&::AIL_set_redist_directory),Expected34>::value,"AIL_set_redist_directory exact signature");
typedef void (AILCALL *Expected35)(HDIGDRIVER, S32);
static_assert(std::is_same<decltype(&::AIL_set_room_type),Expected35>::value,"AIL_set_room_type exact signature");
typedef void (AILCALL *Expected36)(HSAMPLE, F32, F32, S32);
static_assert(std::is_same<decltype(&::AIL_set_sample_3D_distances),Expected36>::value,"AIL_set_sample_3D_distances exact signature");
typedef void (AILCALL *Expected37)(HSAMPLE, F32, F32, F32);
static_assert(std::is_same<decltype(&::AIL_set_sample_3D_position),Expected37>::value,"AIL_set_sample_3D_position exact signature");
typedef void (AILCALL *Expected38)(HSAMPLE, F32, F32, F32);
static_assert(std::is_same<decltype(&::AIL_set_sample_3D_velocity_vector),Expected38>::value,"AIL_set_sample_3D_velocity_vector exact signature");
typedef S32 (AILCALL *Expected39)(HSAMPLE, void const FAR *, S32);
static_assert(std::is_same<decltype(&::AIL_set_sample_file),Expected39>::value,"AIL_set_sample_file exact signature");
typedef void (AILCALL *Expected40)(HSAMPLE, S32, S32);
static_assert(std::is_same<decltype(&::AIL_set_sample_loop_block),Expected40>::value,"AIL_set_sample_loop_block exact signature");
typedef void (AILCALL *Expected41)(HSAMPLE, S32);
static_assert(std::is_same<decltype(&::AIL_set_sample_loop_count),Expected41>::value,"AIL_set_sample_loop_count exact signature");
typedef void (AILCALL *Expected42)(HSAMPLE, S32);
static_assert(std::is_same<decltype(&::AIL_set_sample_ms_position),Expected42>::value,"AIL_set_sample_ms_position exact signature");
typedef void (AILCALL *Expected43)(HSAMPLE, F32);
static_assert(std::is_same<decltype(&::AIL_set_sample_obstruction),Expected43>::value,"AIL_set_sample_obstruction exact signature");
typedef void (AILCALL *Expected44)(HSAMPLE, F32);
static_assert(std::is_same<decltype(&::AIL_set_sample_occlusion),Expected44>::value,"AIL_set_sample_occlusion exact signature");
typedef void (AILCALL *Expected45)(HSAMPLE, S32);
static_assert(std::is_same<decltype(&::AIL_set_sample_playback_rate),Expected45>::value,"AIL_set_sample_playback_rate exact signature");
typedef void (AILCALL *Expected46)(HSAMPLE, U32);
static_assert(std::is_same<decltype(&::AIL_set_sample_position),Expected46>::value,"AIL_set_sample_position exact signature");
typedef void (AILCALL *Expected47)(HSAMPLE, F32, F32);
static_assert(std::is_same<decltype(&::AIL_set_sample_reverb_levels),Expected47>::value,"AIL_set_sample_reverb_levels exact signature");
typedef void (AILCALL *Expected48)(HSAMPLE, F32, F32);
static_assert(std::is_same<decltype(&::AIL_set_sample_volume_levels),Expected48>::value,"AIL_set_sample_volume_levels exact signature");
typedef void (AILCALL *Expected49)(HSTREAM, S32, S32);
static_assert(std::is_same<decltype(&::AIL_set_stream_loop_block),Expected49>::value,"AIL_set_stream_loop_block exact signature");
typedef void (AILCALL *Expected50)(HSTREAM, S32);
static_assert(std::is_same<decltype(&::AIL_set_stream_loop_count),Expected50>::value,"AIL_set_stream_loop_count exact signature");
typedef void (AILCALL *Expected51)(HSTREAM, S32);
static_assert(std::is_same<decltype(&::AIL_set_stream_ms_position),Expected51>::value,"AIL_set_stream_ms_position exact signature");
typedef void (AILCALL *Expected52)(void);
static_assert(std::is_same<decltype(&::AIL_shutdown),Expected52>::value,"AIL_shutdown exact signature");
typedef MSSVECTOR3D FAR * (AILCALL *Expected53)(HDIGDRIVER, S32 FAR *, S32 FAR *, F32 FAR *, MSS_MC_SPEC FAR *);
static_assert(std::is_same<decltype(&::AIL_speaker_configuration),Expected53>::value,"AIL_speaker_configuration exact signature");
typedef void (AILCALL *Expected54)(HSAMPLE);
static_assert(std::is_same<decltype(&::AIL_start_sample),Expected54>::value,"AIL_start_sample exact signature");
typedef void (AILCALL *Expected55)(HSTREAM);
static_assert(std::is_same<decltype(&::AIL_start_stream),Expected55>::value,"AIL_start_stream exact signature");
typedef S32 (AILCALL *Expected56)(void);
static_assert(std::is_same<decltype(&::AIL_startup),Expected56>::value,"AIL_startup exact signature");
typedef void (AILCALL *Expected57)(HSAMPLE);
static_assert(std::is_same<decltype(&::AIL_stop_sample),Expected57>::value,"AIL_stop_sample exact signature");
typedef void (AILCALL *Expected58)(HSTREAM, S32 FAR *, S32 FAR *);
static_assert(std::is_same<decltype(&::AIL_stream_ms_position),Expected58>::value,"AIL_stream_ms_position exact signature");
typedef HSAMPLE (AILCALL *Expected59)(HSTREAM);
static_assert(std::is_same<decltype(&::AIL_stream_sample_handle),Expected59>::value,"AIL_stream_sample_handle exact signature");
typedef S32 (AILCALL *Expected60)(HSTREAM);
static_assert(std::is_same<decltype(&::AIL_stream_status),Expected60>::value,"AIL_stream_status exact signature");
typedef void (AILCALL *Expected61)(void);
static_assert(std::is_same<decltype(&::AIL_unlock),Expected61>::value,"AIL_unlock exact signature");
typedef void (AILCALLBACK *Expected_AILSAMPLECB)(HSAMPLE);
static_assert(std::is_same<AILSAMPLECB,Expected_AILSAMPLECB>::value,"AILSAMPLECB");
typedef void (AILCALLBACK *Expected_AILSTREAMCB)(HSTREAM);
static_assert(std::is_same<AILSTREAMCB,Expected_AILSTREAMCB>::value,"AILSTREAMCB");
typedef U32 (AILCALLBACK *Expected_AIL_file_open_callback)(MSS_FILE const*,UINTa*);
static_assert(std::is_same<AIL_file_open_callback,Expected_AIL_file_open_callback>::value,"AIL_file_open_callback");
typedef void (AILCALLBACK *Expected_AIL_file_close_callback)(UINTa);
static_assert(std::is_same<AIL_file_close_callback,Expected_AIL_file_close_callback>::value,"AIL_file_close_callback");
typedef S32 (AILCALLBACK *Expected_AIL_file_seek_callback)(UINTa,S32,U32);
static_assert(std::is_same<AIL_file_seek_callback,Expected_AIL_file_seek_callback>::value,"AIL_file_seek_callback");
typedef U32 (AILCALLBACK *Expected_AIL_file_read_callback)(UINTa,void*,U32);
static_assert(std::is_same<AIL_file_read_callback,Expected_AIL_file_read_callback>::value,"AIL_file_read_callback");
static_assert(sizeof(U32)==4 && sizeof(S32)==4 && sizeof(F32)==4 && sizeof(MSS_MC_SPEC)==4,"scalar widths");
static_assert(std::is_signed<S32>::value && std::is_unsigned<U32>::value && std::is_signed<SINTa>::value,"signedness");
static_assert(sizeof(SINTa)==sizeof(void*) && sizeof(UINTa)==sizeof(void*),"address-sized scalars");
